import type { Metadata } from "next";
import { Providers } from "@/shared/providers";
import { ModeToggle } from "@/shared/components/custom/toggle-theme";
import { geistSans, geistMono } from "@/shared/fonts";
import "@/shared/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = async ({ children }: RootLayoutProps) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <h1 className="text-4xl underline">Recipes</h1>
          <ModeToggle />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
