import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import { unstable_ViewTransition as ViewTransition } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1600px] mx-auto`}
      >
        <header className="relative px-6 py-6 mb-20 bg-gray-900/80 backdrop-blur-md border-b border-gray-800/50 rounded-b-3xl">
          <Link href="/">
            <div className="max-w-[1600px] mx-auto flex flex-wrap items-center justify-between">
              <div className="flex items-center ml-28 md:ml-32">
                <div className="pt-1 flex flex-col">
                  <div className="text-2xl md:text-3xl font-bold text-white hover:text-emerald-400 transition-colors">
                    Cascade Tone
                  </div>
                  <p className="text-xs md:text-sm text-gray-400 transition-colors">
                    Premium Handcrafted Guitars
                  </p>
                </div>
              </div>
            </div>

            <div className="absolute -bottom-14 left-4 w-28 h-28 overflow-visible">
              <div className="w-full h-full relative">
                <div className="absolute inset-0 bg-emerald-500/20 rounded-full filter blur-xl animate-pulse"></div>
                <img
                  src="/logo.png"
                  alt="Cascade Tone Logo"
                  className="w-full h-full object-contain relative z-10"
                />
              </div>
            </div>
          </Link>
        </header>
        <main>
          {/* <ViewTransition> */}
          {children}
          {/* </ViewTransition> */}
        </main>
      </body>
    </html>
  );
}
